runtime: python37
handlers:
- url: /
  static_files: frontend/index.html
  upload: frontend/index.html
- url: /favicon\.ico
  static_files: frontend/favicon.ico
  upload: frontend/favicon\.ico
- url: /static/css
  mime_type: text/css
  static_dir: frontend/static/css
- url: /static/js
  mime_type: text/javascript
  static_dir: frontend/static/js
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
env_variables:
  algolia_app_id: '9JZ8KBSETQ'
  algolia_ro_api_key: '62beeb4c091e9e6d907d1556fd1eb4f9'